Repository BinaryStudioAcademy/bsa-2023-squirrel, pull requests merged in 2023-08, with the labels that each got.

#1 Update README.md
  README.md
Labels: enhancement

#5 squirrel-29: + created a service with HTTP client
  frontend/src/app/core/services/http-internal.service.ts
Labels: enhancement

#11 Add package-lock to .gitignore
  frontend/.gitignore
Labels: enhancement

#7 sql-10: As a developer I need to have material UI module in our app
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/material/material.module.ts
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/landing/landing.module.ts
  frontend/src/styles/global.sass
  frontend/yarn.lock
Labels: enhancement

#14 delete package-lock
  frontend/package-lock.json
Labels: enhancement

#2 sql: add MapControllers
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Program.cs
Labels: enhancement

#13 sql-28: Add Shared Button Component
  frontend/src/app/shared/components/button/button.component.html
  frontend/src/app/shared/components/button/button.component.sass
  frontend/src/app/shared/components/button/button.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#3 sql-30: As a user I want to have console app
  backend/Squirrel.All.sln
  backend/Squirrel.ConsoleApp.sln
  backend/Squirrel.ConsoleApp/Program.cs
  backend/Squirrel.ConsoleApp/Squirrel.ConsoleApp.csproj
Labels: enhancement

#18 Used file-scoped namespaces and fixed typo 'Extentions'
  backend/Squirrel.ConsoleApp/Program.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Interfaces/ISampleService.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/MappingProfiles/SampleProfile.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Services/Abstract/BaseService.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Services/SampleService.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Sample/NewSampleDto.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Sample/SampleDto.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Context/EntityConfigurations/SampleConfig.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Context/ModelBuilderExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Context/SquirrelCoreContext.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Entities/Common/AuditEntity/AuditEntity.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Entities/Common/Entity.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Entities/Sample.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Controllers/SampleController.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extensions/ApplicationBuilderExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extensions/ServiceCollectionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extentions/ApplicationBuilderExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Middlewares/GenericExceptionHandlerMiddleware.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Program.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Validators/Sample/NewSampleDtoValidator.cs
  backend/Squirrel.Notifier/Squirrel.Notifier.WebAPI/Controllers/BroadcastController.cs
  backend/Squirrel.Notifier/Squirrel.Notifier.WebAPI/Hubs/BroadcastHub.cs
  backend/Squirrel.Notifier/Squirrel.Notifier.WebAPI/Hubs/Interfaces/IBroadcastHubClient.cs
  backend/Squirrel.Notifier/Squirrel.Notifier.WebAPI/Program.cs
Labels: reviewed

#16 sql-38: Add Toastr Notofication
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/core/services/notification.service.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles/index.sass
Labels: enhancement, reviewed

#10 sql-2: Add Registration Page
  frontend/src/app/app-routing.module.ts
  frontend/src/app/models/auth/user-register-dto.ts
  frontend/src/app/modules/authentication/authentication-page/authentication-page.component.html
  frontend/src/app/modules/authentication/authentication-page/authentication-page.component.sass
  frontend/src/app/modules/authentication/authentication-page/authentication-page.component.ts
  frontend/src/app/modules/authentication/authentication-routing.module.ts
  frontend/src/app/modules/authentication/authentication.module.ts
  frontend/src/app/modules/authentication/logo/logo.component.html
  frontend/src/app/modules/authentication/logo/logo.component.sass
  frontend/src/app/modules/authentication/logo/logo.component.ts
  frontend/src/app/modules/authentication/registration/registration.component.html
  frontend/src/app/modules/authentication/registration/registration.component.sass
  frontend/src/app/modules/authentication/registration/registration.component.ts
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
  frontend/src/app/modules/landing/landing-routing.module.ts
  frontend/src/app/modules/landing/landing.module.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/assets/hide-1.svg
  frontend/src/assets/hide-2.svg
  frontend/src/assets/logo-bg.png
  frontend/src/styles/color.sass
  frontend/src/styles/global.sass
  frontend/yarn.lock
Labels: enhancement, reviewed

#22 52: Add general input component
  frontend/src/app/modules/authentication/registration/registration.component.html
  frontend/src/app/modules/authentication/registration/registration.component.ts
  frontend/src/app/shared/components/input/input.component.html
  frontend/src/app/shared/components/input/input.component.sass
  frontend/src/app/shared/components/input/input.component.ts
  frontend/src/app/shared/helpers/validations-fn.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#17 1 Add database schema
  README.md
Labels: documentation

#21 49: styles for btn component
  .gitignore
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/shared/components/button/button.component.html
  frontend/src/app/shared/components/button/button.component.sass
  frontend/src/app/shared/components/button/button.component.ts
  frontend/src/assets/fonts/fonts-montserrat.sass
  frontend/src/assets/fonts/montserrat/Montserrat-Bold.ttf
  frontend/src/assets/fonts/montserrat/Montserrat-VariableFont_wght.ttf
  frontend/src/styles/color.sass
  frontend/src/styles/index.sass
Labels: enhancement

#25 sql-47: As a developer I need a library to compare two strings (files)
  backend/Squirrel.Core/Squirrel.Core.BLL/Interfaces/ITextService.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Services/TextService.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Squirrel.Core.BLL.csproj
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Text/DiffLineResult.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Text/InLineDiffResultDto.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Text/SideBySideDiffResultDto.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Text/TextPairRequestDto.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Squirrel.Core.Common.csproj
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extensions/ServiceCollectionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Program.cs
Labels: enhancement, reviewed

#26 41: docker container with db that can be used as a test one
  test-db-container/Dockerfile
  test-db-container/README.md
  test-db-container/init.sql
Labels: enhancement

#35 58: Add more parameters for the generic input component
  frontend/src/app/modules/authentication/login/login.component.html
  frontend/src/app/modules/authentication/registration/registration.component.html
  frontend/src/app/shared/components/input/input.component.html
  frontend/src/app/shared/components/input/input.component.sass
  frontend/src/app/shared/components/input/input.component.ts
Labels: enhancement

#19 sql-36: As a developer I want to know how to implement log in via Google
  backend/Squirrel.Core/Squirrel.Core.BLL/Interfaces/IAuthService.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Services/AuthService.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Squirrel.Core.BLL.csproj
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Auth/AccessToken.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Auth/AuthenticationSettings.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Auth/GoogleToken.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Users/AccessTokenDTO.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Users/AuthUserDTO.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Users/UserDTO.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Controllers/AuthController.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extensions/ServiceCollectionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Program.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/appsettings.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/models/auth/google-auth-dto.ts
  frontend/src/app/models/auth/token-dto.ts
  frontend/src/app/models/auth/user-auth-dto.ts
  frontend/src/app/models/user/user-dto.ts
  frontend/src/app/models/user/user-login-dto.ts
  frontend/src/app/models/user/user-register-dto.ts
  frontend/src/app/modules/authentication/login/login.component.html
  frontend/src/app/modules/authentication/login/login.component.ts
  frontend/src/app/modules/authentication/registration/registration.component.ts
  frontend/src/app/services/external-auth.service.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  frontend/src/index.html
  frontend/yarn.lock
Labels: reviewed

#30 40 - As a user I want to have registration flow
  backend/Squirrel.Core/Squirrel.Core.BLL/Extensions/ServiceCollectionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/MappingProfiles/UserProfile.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Services/AuthService.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Squirrel.Core.BLL.csproj
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Auth/UserRegisterDto.cs
  backend/Squirrel.Core/Squirrel.Core.Common/DTO/Error/ErrorDetailsDto.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Enums/ErrorType.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Exceptions/Abstract/RequestException.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Exceptions/EmailAlreadyRegisteredException.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Exceptions/IncorrectPasswordConfirmationException.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Exceptions/UsernameAlreadyRegisteredException.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Extensions/ExceptionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.Common/JWT/JwtFactory.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Security/BytesGenerator.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Security/SecurityUtils.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Context/EntityConfigurations/RefreshTokenConfig.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Context/EntityConfigurations/UserConfig.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Context/SquirrelCoreContext.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Entities/RefreshToken.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Entities/User.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Migrations/20230822082848_AddedRefreshTokens.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Migrations/20230823174915_AddedRefreshTokensAndUsers.Designer.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Migrations/20230823174915_AddedRefreshTokensAndUsers.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Migrations/SquirrelCoreContextModelSnapshot.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Controllers/AuthController.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extensions/ServiceCollectionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Middlewares/GenericExceptionHandlerMiddleware.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Program.cs
  frontend/src/app/app-routing.module.ts
  frontend/src/app/core/interceptors/error.interceptor.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/models/auth/access-token-dto.ts
  frontend/src/app/models/auth/user-auth-dto.ts
  frontend/src/app/models/auth/user-login-dto.ts
  frontend/src/app/models/error/error-details-dto.ts
  frontend/src/app/models/error/error-type.ts
  frontend/src/app/modules/authentication/authentication-routing.module.ts
  frontend/src/app/modules/authentication/login/login.component.html
  frontend/src/app/modules/authentication/login/login.component.ts
  frontend/src/app/modules/authentication/registration/registration.component.html
  frontend/src/app/modules/authentication/registration/registration.component.ts
  frontend/src/app/services/external-auth.service.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement, reviewed

#38 57 Mechanism to save console as one .exe file
  .gitignore
  CreateExeOfConsoleApp.cmd
Labels: reviewed

#39 61: not create test files on component generation
  frontend/angular.json
Labels: reviewed

#41 51: As a user I want to have PRs page content
  frontend/package.json
  frontend/src/app/material/material.module.ts
  frontend/src/app/models/branch/branch.ts
  frontend/src/app/models/comment/comment.ts
  frontend/src/app/models/pull-request/pull-request.ts
  frontend/src/app/models/user/user.ts
  frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.html
  frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.sass
  frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.ts
  frontend/src/app/modules/pull-request/pull-request.module.ts
  frontend/src/app/modules/pull-request/pull-request/pull-request.component.html
  frontend/src/app/modules/pull-request/pull-request/pull-request.component.sass
  frontend/src/app/modules/pull-request/pull-request/pull-request.component.ts
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.html
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.sass
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
  frontend/src/app/shared/helpers/user-predicates.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/assets/arrow_right_icon.svg
  frontend/src/assets/expand_more_24px.svg
  frontend/src/assets/sms_icon.svg
  frontend/src/styles/color.sass
  frontend/yarn.lock
Labels: enhancement

#43 59: Add authorization flow
  backend/Squirrel.Core/Squirrel.Core.BLL/Services/AuthService.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Enums/ErrorType.cs
  backend/Squirrel.Core/Squirrel.Core.Common/Exceptions/InvalidEmailOrPasswordException.cs
  frontend/src/app/app-routing.module.ts
  frontend/src/app/core/core.module.ts
  frontend/src/app/core/guards/auth.guard.ts
  frontend/src/app/core/interceptors/jwt.interceptor.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/authentication/login/login.component.ts
Labels: enhancement

#36 50: mechanism to find all functions sps used in another sp function
  backend/Squirrel.Core/Squirrel.Core.BLL/Interfaces/IDependencyAnalyzer.cs
  backend/Squirrel.Core/Squirrel.Core.BLL/Services/DependencyAnalyzer.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#46 67: shared avatar component
  frontend/src/app/shared/components/avatar/avatar.component.html
  frontend/src/app/shared/components/avatar/avatar.component.sass
  frontend/src/app/shared/components/avatar/avatar.component.ts
  frontend/src/app/shared/helpers/hsl-generator.service.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#42 56: As a developer I want to have service to get all actions from the console app
  backend/Squirrel.ConsoleApp.BL/Interfaces/IConnectionFileService.cs
  backend/Squirrel.ConsoleApp.BL/Interfaces/IDatabaseService.cs
  backend/Squirrel.ConsoleApp.BL/Interfaces/IDbQueryProvider.cs
  backend/Squirrel.ConsoleApp.BL/Interfaces/IGetActionsService.cs
  backend/Squirrel.ConsoleApp.BL/Services/Abstract/BaseDbService.cs
  backend/Squirrel.ConsoleApp.BL/Services/ConnectionFileService.cs
  backend/Squirrel.ConsoleApp.BL/Services/PostgreSqlService.cs
  backend/Squirrel.ConsoleApp.BL/Services/SqlServerService.cs
  backend/Squirrel.ConsoleApp.BL/Squirrel.ConsoleApp.BL.csproj
  backend/Squirrel.ConsoleApp.Models/ConnectionString.cs
  backend/Squirrel.ConsoleApp.Models/DbEngine.cs
  backend/Squirrel.ConsoleApp.Models/DbSettings.cs
  backend/Squirrel.ConsoleApp.Models/ErrorCode.cs
  backend/Squirrel.ConsoleApp.Models/Models/DbEngine.cs
  backend/Squirrel.ConsoleApp.Models/QueryResultTable.cs
  backend/Squirrel.ConsoleApp.Models/Squirrel.ConsoleApp.Models.csproj
  backend/Squirrel.ConsoleApp/Controllers/SettingController.cs
  backend/Squirrel.ConsoleApp/Extensions/ExceptionFilterExtensions.cs
  backend/Squirrel.ConsoleApp/Program.cs
  backend/Squirrel.ConsoleApp/Providers/PostgreSqlQueryProvider.cs
  backend/Squirrel.ConsoleApp/Providers/PostgreSqlScripts/GetObjects.cs
  backend/Squirrel.ConsoleApp/Providers/PostgreSqlScripts/GetTables.cs
  backend/Squirrel.ConsoleApp/Providers/PostgreSqlScripts/GetUserDefinedTypes.cs
  backend/Squirrel.ConsoleApp/Providers/SqlServerQueryProvider.cs
  backend/Squirrel.ConsoleApp/Providers/SqlServerScripts/GetObjects.cs
  backend/Squirrel.ConsoleApp/Providers/SqlServerScripts/GetTables.cs
  backend/Squirrel.ConsoleApp/Providers/SqlServerScripts/GetUserDefinedTypes.cs
  backend/Squirrel.ConsoleApp/Services/DatabaseFactory.cs
  backend/Squirrel.ConsoleApp/Services/GetActionsService.cs
  backend/Squirrel.ConsoleApp/Squirrel.ConsoleApp.csproj
  backend/Squirrel.ConsoleApp/Startup.cs
  backend/Squirrel.ConsoleApp/appsettings.json
Labels: enhancement

#48 68: + placed logo according to design
  frontend/src/app/modules/authentication/logo/logo.component.html
  frontend/src/app/modules/authentication/logo/logo.component.sass
  frontend/src/app/shared/components/sidebar/sidebar.component.html
  frontend/src/app/shared/components/sidebar/sidebar.component.sass
  frontend/src/assets/big-logo.svg
  frontend/src/assets/logo.png
  frontend/src/assets/logo.svg
Labels: enhancement

#47 63: As a user I want to have SQL microservice
  backend/Squirrel.All.sln
  backend/Squirrel.Core/Squirrel.Core.BLL/Squirrel.Core.BLL.csproj
  backend/Squirrel.Core/Squirrel.Core.DAL/Extensions/ApplicationBuilderExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Extensions/ServiceCollectionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.DAL/Squirrel.Core.DAL.csproj
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Extensions/ServiceCollectionExtensions.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/Program.cs
  backend/Squirrel.Core/Squirrel.Core.WebAPI/appsettings.json
  backend/Squirrel.Shared/DTO/Text/DiffLineResult.cs
  backend/Squirrel.Shared/DTO/Text/InLineDiffResultDto.cs
  backend/Squirrel.Shared/DTO/Text/SideBySideDiffResultDto.cs
  backend/Squirrel.Shared/DTO/Text/TextPairRequestDto.cs
  backend/Squirrel.Shared/Squirrel.Shared.csproj
  backend/Squirrel.SqlService.sln
  backend/Squirrel.SqlService/Squirrel.SqlService.BLL/Interfaces/IDependencyAnalyzer.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.BLL/Interfaces/IMongoService.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.BLL/Interfaces/ITextService.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.BLL/Models/Options/MongoDatabaseConnectionSettings.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.BLL/Services/DependencyAnalyzer.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.BLL/Services/MongoService.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.BLL/Services/TextService.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.BLL/Squirrel.SqlService.BLL.csproj
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/Controllers/BlobController.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/Controllers/TextDifferenceController.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/Extensions/ServiceCollectionExtensions.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/Program.cs
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/Properties/launchSettings.json
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/Properties/serviceDependencies.json
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/Properties/serviceDependencies.local.json
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/Squirrel.SqlService.WebApi.csproj
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/appsettings.Development.json
  backend/Squirrel.SqlService/Squirrel.SqlService.WebApi/appsettings.json
Labels: enhancement

#51 37: confirmation modal component
  frontend/package.json
  frontend/src/app/material/material.module.ts
  frontend/src/app/models/confirmation-modal/confirmation-modal.ts
  frontend/src/app/modules/main/main-page/headers/main-header/main-header.component.ts
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main-page/main-page.component.ts
  frontend/src/app/shared/components/confirmation-modal/confirmation-modal.component.html
  frontend/src/app/shared/components/confirmation-modal/confirmation-modal.component.sass
  frontend/src/app/shared/components/confirmation-modal/confirmation-modal.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/yarn.lock
Labels: enhancement

#55 71: Bugfix with text overflow in button component
  frontend/src/app/shared/components/button/button.component.sass
Labels: bug

#58 62: Add main page
  frontend/angular.json
  frontend/src/app/modules/authentication/login/login.component.html
  frontend/src/app/modules/authentication/login/login.component.sass
  frontend/src/app/modules/authentication/registration/registration.component.sass
  frontend/src/app/modules/changes/changes-routing.module.ts
  frontend/src/app/modules/changes/changes.module.ts
  frontend/src/app/modules/changes/changes/changes.component.html
  frontend/src/app/modules/changes/changes/changes.component.sass
  frontend/src/app/modules/changes/changes/changes.component.ts
  frontend/src/app/modules/changes/solution/solution.component.html
  frontend/src/app/modules/changes/solution/solution.component.sass
  frontend/src/app/modules/changes/solution/solution.component.ts
  frontend/src/app/modules/main/main-page/headers/main-header/main-header.component.html
  frontend/src/app/modules/main/main-page/headers/main-header/main-header.component.sass
  frontend/src/app/modules/main/main-page/headers/navbar-header/navbar-header.component.sass
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main-page/main-page.component.sass
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.sass
  frontend/src/app/modules/pull-request/pull-request-routing.module.ts
  frontend/src/app/modules/pull-request/pull-request.module.ts
  frontend/src/app/modules/pull-request/pull-request/pull-request.component.sass
  frontend/src/app/shared/components/barrier/barrier.component.sass
  frontend/src/app/shared/components/button/button.component.sass
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.sass
  frontend/src/app/shared/components/dropdown/dropdown.component.sass
  frontend/src/app/shared/components/input/input.component.sass
  frontend/src/app/shared/components/profile-menu/profile-menu.component.html
  frontend/src/app/shared/components/profile-menu/profile-menu.component.sass
  frontend/src/app/shared/components/sidebar/sidebar.component.html
  frontend/src/app/shared/components/sidebar/sidebar.component.sass
  frontend/src/app/shared/components/tree/tree.component.html
  frontend/src/app/shared/components/tree/tree.component.sass
  frontend/src/assets/full-size.svg
  frontend/src/styles/global.sass
  frontend/src/styles/reusable.sass
  frontend/src/styles/weights.sass
  frontend/yarn.lock
Labels: enhancement
